export const ROLES = ["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","hr","finance","compliance","guard","client_administrator","client_user"] as const;
export type Role = (typeof ROLES)[number];
export const roleLabels: Record<Role,string> = {platform_owner:"Platform Owner",super_administrator:"Super Administrator",administrator:"Administrator",operations_manager:"Operations Manager",area_manager:"Area Manager",site_supervisor:"Site Supervisor",hr:"HR",finance:"Finance",compliance:"Compliance",guard:"Guard",client_administrator:"Client Administrator",client_user:"Client User"};
export const internalRoles: Role[] = ["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","hr","finance","compliance","guard"];
export function isRole(value:unknown):value is Role{return typeof value==="string"&&(ROLES as readonly string[]).includes(value);}
export const navigationAccess: Record<string,Role[]> = {
  "/":[...ROLES],"/clients":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor"],"/sites":[...internalRoles,"client_administrator","client_user"],"/workforce":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","hr"],"/roster":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor"],"/attendance":[...internalRoles,"client_administrator","client_user"],"/patrols":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","guard","client_administrator","client_user"],"/incidents":[...internalRoles,"client_administrator","client_user"],"/leave":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","hr","guard"],"/inventory":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","finance","compliance"],"/compliance":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","compliance"],"/reports":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","hr","finance","compliance"],"/intelligence":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","hr","finance","compliance"],"/command":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor"],"/site-risk":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","compliance"],"/operations-map":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","guard","client_administrator"],"/field":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","guard"],"/client-portal":["platform_owner","super_administrator","administrator","operations_manager","client_administrator","client_user"],"/sla":["platform_owner","super_administrator","administrator","operations_manager","area_manager"],
"/platform/digital-twin":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor"],"/platform/workforce-intelligence":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","hr","finance"],"/platform/intelligent-rostering":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","hr"],"/platform/case-management":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","compliance"],"/platform/sop-workflows":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","compliance"],"/platform/financial-intelligence":["platform_owner","super_administrator","administrator","operations_manager","finance"],"/platform/audit-security":["platform_owner","super_administrator","administrator","compliance"],"/platform/automated-reporting":["platform_owner","super_administrator","administrator","operations_manager","area_manager","site_supervisor","hr","finance","compliance"],"/platform/integrations":["platform_owner","super_administrator","administrator"],"/platform/api":["platform_owner","super_administrator","administrator"],"/platform/marketplace":["platform_owner","super_administrator","administrator"],"/platform/benchmarking":["platform_owner","super_administrator","administrator","operations_manager","area_manager"]};
export function canAccess(role:Role|null|undefined,allowed:Role[]){return !!role&&allowed.includes(role);}
export function canAccessPath(role:Role|null|undefined,path:string){return canAccess(role,navigationAccess[path]??[]);}
