import {listRows,dashboardMetrics} from "./api";
import type {DashboardMetrics} from "../types";
export type RiskLevel="low"|"medium"|"high"|"critical";
export type SiteRisk={siteId:string;siteName:string;risk:number;level:RiskLevel;drivers:string[]};
export type OperationalSnapshot={metrics:DashboardMetrics;sites:Record<string,unknown>[];employees:Record<string,unknown>[];attendance:Record<string,unknown>[];incidents:Record<string,unknown>[];compliance:Record<string,unknown>[];patrols:Record<string,unknown>[]};
function level(score:number):RiskLevel{return score>=80?"critical":score>=60?"high":score>=35?"medium":"low"}
function numericStatus(value:unknown, values:string[]):number{return typeof value==="string"&&values.includes(value)?1:0}
export async function operationalSnapshot():Promise<OperationalSnapshot>{const [metrics,sites,employees,attendance,incidents,compliance,patrols]=await Promise.all([dashboardMetrics(),listRows("sites"),listRows("employees"),listRows("attendance"),listRows("incidents"),listRows("compliance_items"),listRows("patrol_routes")]);return{metrics,sites,employees,attendance,incidents,compliance,patrols}}
export function calculateSiteRisks(snapshot:OperationalSnapshot):SiteRisk[]{return snapshot.sites.map(site=>{const id=String(site.id??"");const name=String(site.name??"Unnamed site");const incidents=snapshot.incidents.filter(x=>String(x.site_id??"")===id);const compliance=snapshot.compliance.filter(x=>String(x.site_id??"")===id);const staff=snapshot.employees.filter(x=>String(x.site_id??"")===id&&x.employment_status==="active");const incidentPressure=Math.min(35,incidents.filter(x=>numericStatus(x.status,["open","under_review","escalated"])).length*10);const compliancePressure=Math.min(25,compliance.filter(x=>numericStatus(x.status,["expired","expiring"])).length*8);const staffingPressure=staff.length===0?20:0;const score=Math.min(100,incidentPressure+compliancePressure+staffingPressure);const drivers:string[]=[];if(incidentPressure)drivers.push("Open incident pressure");if(compliancePressure)drivers.push("Compliance exceptions");if(staffingPressure)drivers.push("No active workforce linked");return{siteId:id,siteName:name,risk:score,level:level(score),drivers:drivers.length?drivers:["No high-signal exception detected"]}}).sort((a,b)=>b.risk-a.risk)}
export function slaPressure(snapshot:OperationalSnapshot){const open=snapshot.incidents.filter(x=>numericStatus(x.status,["open","under_review","escalated"])).length;const exceptions=snapshot.compliance.filter(x=>numericStatus(x.status,["expired","expiring"])).length;const missingAttendance=snapshot.attendance.filter(x=>x.status==="absent"||x.status==="late").length;return{openIncidents:open,complianceExceptions:exceptions,attendanceExceptions:missingAttendance,total:open+exceptions+missingAttendance,level:level(Math.min(100,open*12+exceptions*10+missingAttendance*5))}}
