import {useCallback,useEffect,useMemo,useState} from "react";
import {BrainCircuit,RefreshCw,Sparkles,ShieldAlert,TrendingUp,Users,Building2,ClipboardCheck,Clock3} from "lucide-react";
import {Card,Button,Spinner} from "../components/ui";
import ErrorState from "../components/ErrorState";
import {intelligenceLabel,listInsights,runIntelligence,type Insight,type IntelligenceType} from "../services/intelligence";

const TYPES:IntelligenceType[]=["executive","workforce","incident","site","compliance","attendance","anomaly"];
const icons={executive:Sparkles,workforce:Users,incident:ShieldAlert,site:Building2,compliance:ClipboardCheck,attendance:Clock3,anomaly:TrendingUp,summary:Sparkles,risk:ShieldAlert,trend:TrendingUp,opportunity:Sparkles,recommendation:Sparkles};
const severityClass:Record<Insight["severity"],string>={info:"bg-slate-100 text-slate-700",low:"bg-cyan-50 text-cyan-800",medium:"bg-amber-50 text-amber-800",high:"bg-orange-50 text-orange-800",critical:"bg-red-50 text-red-800"};

function InsightCard({item}:{item:Insight}){const Icon=icons[item.insight_type]??Sparkles;return <Card className="p-5"><div className="flex items-start gap-4"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-cyan-50 text-cyan-700"><Icon size={19}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={"rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-wider "+severityClass[item.severity]}>{item.severity}</span><span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{item.insight_type}</span>{item.confidence!==null&&<span className="text-[10px] font-semibold text-slate-400">{Math.round(item.confidence*100)}% confidence</span>}</div><h3 className="mt-2 text-base font-bold text-slate-900">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.summary}</p>{item.rationale&&<div className="mt-4 rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Why this surfaced</p><p className="mt-1 text-xs leading-5 text-slate-600">{item.rationale}</p></div>}{item.recommended_actions.length>0&&<div className="mt-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Recommended operational actions</p><ul className="mt-2 space-y-1 text-xs text-slate-600">{item.recommended_actions.map((action,index)=><li key={index}>• {typeof action==="string"?action:JSON.stringify(action)}</li>)}</ul></div>}</div></div></Card>}

export default function IntelligencePage(){const[items,setItems]=useState<Insight[]>([]);const[selected,setSelected]=useState<IntelligenceType>("executive");const[loading,setLoading]=useState(true);const[running,setRunning]=useState(false);const[error,setError]=useState("");
const load=useCallback(async()=>{setLoading(true);setError("");try{setItems(await listInsights())}catch(e){setError(e instanceof Error?e.message:"Unable to load intelligence.")}finally{setLoading(false)}},[]);
useEffect(()=>{void load()},[load]);
const filtered=useMemo(()=>items.filter(x=>selected==="executive"||x.insight_type==="summary"||x.insight_type===selected||selected==="anomaly"&&x.insight_type==="anomaly"),[items,selected]);
async function analyze(){setRunning(true);setError("");try{const result=await runIntelligence(selected);setItems(prev=>[...result.insights,...prev].filter((item,index,array)=>array.findIndex(x=>x.id===item.id)===index))}catch(e){setError(e instanceof Error?e.message:"Intelligence analysis failed.")}finally{setRunning(false)}}
return <div className="mx-auto max-w-[1500px] space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-cyan-700"><BrainCircuit size={18}/>Vimba Intelligence</div><h2 className="mt-1 text-3xl font-bold tracking-tight">Operational intelligence</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">A governed intelligence layer that turns tenant-scoped operations data into explainable risks, trends, anomalies and recommended actions.</p></div><div className="flex gap-2"><Button onClick={()=>void load()} disabled={loading||running} variant="secondary"><RefreshCw size={16}/>Refresh</Button><Button onClick={()=>void analyze()} disabled={running}><Sparkles size={16}/>{running?"Analyzing…":"Analyze now"}</Button></div></div>{error&&<ErrorState message={error} onRetry={()=>void load()}/>}<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{TYPES.map(type=>{const Icon=icons[type];return <button key={type} type="button" onClick={()=>setSelected(type)} className={"flex items-center gap-3 rounded-xl border p-3 text-left transition "+(selected===type?"border-cyan-300 bg-cyan-50":"border-slate-200 bg-white hover:bg-slate-50")}><Icon size={17}/><span className="text-sm font-semibold">{intelligenceLabel(type)}</span></button>})}</div>{loading?<Card className="grid min-h-48 place-items-center"><Spinner/></Card>:filtered.length===0?<Card className="p-10 text-center"><BrainCircuit className="mx-auto text-slate-300" size={36}/><h3 className="mt-4 font-bold">No intelligence yet</h3><p className="mt-2 text-sm text-slate-500">Run an analysis to generate governed operational insights for this tenant.</p></Card>:<div className="grid gap-4 xl:grid-cols-2">{filtered.map(item=><InsightCard key={item.id} item={item}/>)}</div>}<Card className="border-dashed p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Governance</p><p className="mt-2 text-sm leading-6 text-slate-600">AI operates inside the authenticated tenant boundary. Insights are stored with their analysis run, evidence and confidence. The engine is designed to recommend operational review—not make autonomous disciplinary, HR or security decisions.</p></Card></div>}
