import {Navigate,Outlet,Route,Routes} from "react-router-dom";import {useEffect,useState} from "react";import {supabase} from "./lib/supabase";import {getMyProfile} from "./services/api";import type {Profile} from "./types";import {navigationAccess} from "./lib/roles";import AppShell from "./components/AppShell";import ProtectedRoute from "./components/ProtectedRoute";import Login from "./pages/Login";import Dashboard from "./pages/Dashboard";import ModulePage from "./pages/ModulePage";import IncidentPage from "./pages/IncidentPage";import AttendancePage from "./pages/AttendancePage";import RosterPage from "./pages/RosterPage";import LeavePage from "./pages/LeavePage";import PatrolPage from "./pages/PatrolPage";import NotFound from "./pages/NotFound";import {Spinner} from "./components/ui";
function ShellRoute({profile}:{profile:Profile|null}){return <ProtectedRoute profile={profile}><AppShell profile={profile!}><Outlet/></AppShell></ProtectedRoute>}
function RoleRoute({profile,path,children}:{profile:Profile|null;path:string;children:React.ReactNode}){return <ProtectedRoute profile={profile} allowedRoles={navigationAccess[path]}>{children}</ProtectedRoute>}
export default function App(){const[profile,setProfile]=useState<Profile|null>(null);const[ready,setReady]=useState(false);useEffect(()=>{if(!supabase){setReady(true);return}let mounted=true;let authGeneration=0;
const loadProfile=async(generation:number)=>{try{const next=await getMyProfile();if(mounted&&generation===authGeneration)setProfile(next)}catch{if(mounted&&generation===authGeneration)setProfile(null)}finally{if(mounted&&generation===authGeneration)setReady(true)}};
supabase.auth.getUser().then(({data,error})=>{if(error||!data.user){if(mounted){authGeneration+=1;setProfile(null);setReady(true)}return}void loadProfile(authGeneration)}).catch(()=>{if(mounted){authGeneration+=1;setProfile(null);setReady(true)}});
const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{authGeneration+=1;const generation=authGeneration;if(!session){if(mounted){setProfile(null);setReady(true)}return}setReady(false);void loadProfile(generation)});
return()=>{mounted=false;subscription.unsubscribe()}},[]);
if(!ready)return <div className="grid min-h-screen place-items-center"><Spinner/></div>;if(!supabase)return <div className="grid min-h-screen place-items-center p-6 text-center"><div><h1 className="text-2xl font-bold">Vimba Ops configuration required</h1><p className="mt-2 text-sm text-slate-500">Set the required environment variables before starting Vimba Ops.</p></div></div>;
return <Routes><Route path="/login" element={profile?<Navigate to="/" replace/>:<Login/>}/><Route element={<ShellRoute profile={profile}/>}><Route index element={<Dashboard profile={profile!}/>}/><Route path="clients" element={<RoleRoute profile={profile} path="/clients"><ModulePage kind="clients"/></RoleRoute>}/><Route path="sites" element={<RoleRoute profile={profile} path="/sites"><ModulePage kind="sites"/></RoleRoute>}/><Route path="workforce" element={<RoleRoute profile={profile} path="/workforce"><ModulePage kind="workforce"/></RoleRoute>}/><Route path="inventory" element={<RoleRoute profile={profile} path="/inventory"><ModulePage kind="inventory"/></RoleRoute>}/><Route path="compliance" element={<RoleRoute profile={profile} path="/compliance"><ModulePage kind="compliance"/></RoleRoute>}/><Route path="reports" element={<RoleRoute profile={profile} path="/reports"><ModulePage kind="reports"/></RoleRoute>}/><Route path="incidents" element={<RoleRoute profile={profile} path="/incidents"><IncidentPage/></RoleRoute>}/><Route path="attendance" element={<RoleRoute profile={profile} path="/attendance"><AttendancePage/></RoleRoute>}/><Route path="roster" element={<RoleRoute profile={profile} path="/roster"><RosterPage/></RoleRoute>}/><Route path="leave" element={<RoleRoute profile={profile} path="/leave"><LeavePage/></RoleRoute>}/><Route path="patrols" element={<RoleRoute profile={profile} path="/patrols"><PatrolPage/></RoleRoute>}/><Route path="*" element={<NotFound/>}/></Route><Route path="*" element={<NotFound/>}/></Routes>;
}
