create extension if not exists pgcrypto;

create schema if not exists private;

create type public.app_role as enum ('platform_owner','super_administrator','administrator','operations_manager','area_manager','site_supervisor','hr','finance','compliance','guard','client_administrator','client_user');
create type public.record_status as enum ('active','inactive','pending','suspended','archived');
create type public.incident_status as enum ('open','under_review','escalated','resolved','closed');
create type public.attendance_status as enum ('scheduled','on_duty','late','early_departure','absent','missed_shift','off_duty');
create type public.leave_status as enum ('pending','approved','rejected','cancelled');
create type public.asset_status as enum ('available','assigned','maintenance','lost','retired');

create table public.tenants(id uuid primary key default gen_random_uuid(),name text not null,legal_name text,registration_number text,status public.record_status not null default 'active',timezone text not null default 'Africa/Johannesburg',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.clients(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,name text not null,account_number text,status public.record_status not null default 'active',billing_email text,phone text,address text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,account_number));
create table public.profiles(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,tenant_id uuid references public.tenants(id) on delete restrict,client_id uuid references public.clients(id) on delete restrict,full_name text not null default '',role public.app_role not null default 'guard',status public.record_status not null default 'pending',employee_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.client_contacts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,client_id uuid not null references public.clients(id) on delete cascade,name text not null,email text,phone text,title text,created_at timestamptz not null default now());
create table public.contracts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,client_id uuid not null references public.clients(id) on delete restrict,contract_number text not null,start_date date not null,end_date date,sla_summary text,billing_terms text,status public.record_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,contract_number));
create table public.sites(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,client_id uuid references public.clients(id) on delete set null,contract_id uuid references public.contracts(id) on delete set null,name text not null,address_line text,city text,province text,postal_code text,latitude numeric(9,6),longitude numeric(9,6),operating_hours text,site_manager text,emergency_contacts jsonb not null default '[]',instructions text,risk_notes text,status public.record_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.posts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,site_id uuid not null references public.sites(id) on delete cascade,name text not null,post_type text not null,required_staff integer not null default 1 check(required_staff>0),required_qualifications text[] not null default '{}',instructions text,status public.record_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.employees(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,employee_number text not null,full_name text not null,email text,phone text,rank text,department text,employment_status public.record_status not null default 'active',hire_date date,termination_date date,emergency_contact jsonb not null default '{}',site_id uuid references public.sites(id) on delete set null,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,employee_number));
alter table public.profiles add constraint profiles_employee_fk foreign key(employee_id) references public.employees(id) on delete set null;
create table public.employee_documents(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete cascade,document_type text not null,document_number text,issue_date date,expiry_date date,storage_path text,verification_status text not null default 'pending',notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.shifts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,site_id uuid not null references public.sites(id) on delete cascade,post_id uuid references public.posts(id) on delete set null,starts_at timestamptz not null,ends_at timestamptz not null,required_staff integer not null default 1 check(required_staff>0),recurrence_rule text,status public.record_status not null default 'active',notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at>starts_at));
create table public.shift_assignments(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,shift_id uuid not null references public.shifts(id) on delete cascade,employee_id uuid not null references public.employees(id) on delete restrict,assignment_status text not null default 'assigned',assigned_at timestamptz not null default now(),unique(shift_id,employee_id));
create table public.attendance(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete restrict,shift_id uuid references public.shifts(id) on delete set null,attendance_date date not null,clock_in timestamptz,clock_out timestamptz,status public.attendance_status not null default 'scheduled',verification_method text,verification_metadata jsonb not null default '{}',supervisor_verified_at timestamptz,supervisor_verified_by uuid references auth.users(id) on delete set null,exception_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.incidents(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,site_id uuid references public.sites(id) on delete set null,reported_by uuid references auth.users(id) on delete set null,title text not null,category text not null default 'general',severity text not null default 'medium' check(severity in ('low','medium','high','critical')),occurred_at timestamptz not null default now(),description text not null,actions_taken text,people_involved jsonb not null default '[]',witnesses jsonb not null default '[]',evidence_paths text[] not null default '{}',status public.incident_status not null default 'open',supervisor_review text,escalated_at timestamptz,resolved_at timestamptz,resolution text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.patrol_routes(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,site_id uuid not null references public.sites(id) on delete cascade,name text not null,description text,status public.record_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.patrol_checkpoints(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,route_id uuid not null references public.patrol_routes(id) on delete cascade,name text not null,sequence_no integer not null check(sequence_no>0),verification_type text not null default 'gps' check(verification_type in ('gps','qr','nfc')),latitude numeric(9,6),longitude numeric(9,6),radius_meters integer,external_reference text,status public.record_status not null default 'active',unique(route_id,sequence_no));
create table public.patrol_schedules(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,route_id uuid not null references public.patrol_routes(id) on delete cascade,post_id uuid references public.posts(id) on delete set null,starts_at timestamptz not null,ends_at timestamptz not null,frequency text,required_runs integer not null default 1,status public.record_status not null default 'active',check(ends_at>starts_at));
create table public.patrol_runs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,schedule_id uuid references public.patrol_schedules(id) on delete set null,route_id uuid not null references public.patrol_routes(id) on delete restrict,employee_id uuid references public.employees(id) on delete set null,started_at timestamptz,completed_at timestamptz,status text not null default 'scheduled',exception_reason text,created_at timestamptz not null default now());
create table public.patrol_checkpoint_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,run_id uuid not null references public.patrol_runs(id) on delete cascade,checkpoint_id uuid not null references public.patrol_checkpoints(id) on delete restrict,observed_at timestamptz not null default now(),verification_method text not null,verification_payload jsonb not null default '{}',verified boolean not null default false,exception_reason text);
create table public.leave_types(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,name text not null,paid boolean not null default true,annual_allowance numeric(8,2),active boolean not null default true,unique(tenant_id,name));
create table public.leave_balances(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete cascade,leave_type_id uuid not null references public.leave_types(id) on delete cascade,period_year integer not null,opening_balance numeric(8,2) not null default 0,accrued numeric(8,2) not null default 0,used numeric(8,2) not null default 0,closing_balance numeric(8,2) generated always as(opening_balance+accrued-used) stored,unique(employee_id,leave_type_id,period_year));
create table public.leave_requests(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete cascade,leave_type_id uuid not null references public.leave_types(id) on delete restrict,start_date date not null,end_date date not null,reason text,supporting_document_path text,status public.leave_status not null default 'pending',reviewed_by uuid references auth.users(id) on delete set null,reviewed_at timestamptz,review_notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date>=start_date));
create table public.assets(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,asset_number text not null,name text not null,category text not null,serial_number text,condition text,status public.asset_status not null default 'available',site_id uuid references public.sites(id) on delete set null,assigned_employee_id uuid references public.employees(id) on delete set null,issued_at timestamptz,returned_at timestamptz,maintenance_due date,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,asset_number));
create table public.asset_assignments(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,asset_id uuid not null references public.assets(id) on delete restrict,employee_id uuid references public.employees(id) on delete set null,site_id uuid references public.sites(id) on delete set null,issued_at timestamptz not null default now(),returned_at timestamptz,issued_by uuid references auth.users(id) on delete set null,returned_by uuid references auth.users(id) on delete set null,notes text);
create table public.compliance_items(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,employee_id uuid references public.employees(id) on delete cascade,site_id uuid references public.sites(id) on delete cascade,subject_name text not null,document_type text not null,document_number text,issue_date date,expiry_date date,status text not null default 'valid' check(status in ('valid','expiring','expired','missing','pending')),storage_path text,verified_by uuid references auth.users(id) on delete set null,verified_at timestamptz,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,recipient_user_id uuid references auth.users(id) on delete cascade,type text not null,title text not null,message text not null,severity text not null default 'info',entity_type text,entity_id uuid,read_at timestamptz,created_at timestamptz not null default now());
create table public.saved_reports(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,name text not null,report_type text not null,filters jsonb not null default '{}',created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create table public.audit_log(id bigint generated always as identity primary key,tenant_id uuid references public.tenants(id) on delete restrict,actor_user_id uuid references auth.users(id) on delete set null,action text not null,entity_type text not null,entity_id uuid,occurred_at timestamptz not null default now(),old_data jsonb,new_data jsonb,request_id text,ip_address inet,user_agent text);

create index profiles_user_idx on public.profiles(user_id);create index profiles_tenant_idx on public.profiles(tenant_id);create index clients_tenant_idx on public.clients(tenant_id);create index sites_tenant_idx on public.sites(tenant_id);create index sites_client_idx on public.sites(client_id);create index employees_tenant_idx on public.employees(tenant_id);create index shifts_tenant_time_idx on public.shifts(tenant_id,starts_at);create index attendance_tenant_date_idx on public.attendance(tenant_id,attendance_date);create index incidents_tenant_status_idx on public.incidents(tenant_id,status);create index patrol_runs_tenant_status_idx on public.patrol_runs(tenant_id,status);create index leave_requests_tenant_status_idx on public.leave_requests(tenant_id,status);create index compliance_tenant_expiry_idx on public.compliance_items(tenant_id,expiry_date);create index notifications_recipient_idx on public.notifications(recipient_user_id,read_at);create index audit_tenant_time_idx on public.audit_log(tenant_id,occurred_at desc);

create or replace function private.current_tenant_id() returns uuid language sql stable security definer set search_path='' as $$select p.tenant_id from public.profiles p where p.user_id=(select auth.uid()) and p.status='active' limit 1$$;
create or replace function private.current_role() returns public.app_role language sql stable security definer set search_path='' as $$select p.role from public.profiles p where p.user_id=(select auth.uid()) and p.status='active' limit 1$$;
create or replace function private.current_client_id() returns uuid language sql stable security definer set search_path='' as $$select p.client_id from public.profiles p where p.user_id=(select auth.uid()) and p.status='active' limit 1$$;
create or replace function private.is_internal() returns boolean language sql stable security definer set search_path='' as $$select coalesce((select private.current_role()) in ('platform_owner','super_administrator','administrator','operations_manager','area_manager','site_supervisor','hr','finance','compliance','guard'),false)$$;
create or replace function private.has_role(roles public.app_role[]) returns boolean language sql stable security definer set search_path='' as $$select coalesce((select private.current_role())=any(roles),false)$$;
revoke all on schema private from public;grant usage on schema private to authenticated;revoke all on all functions in schema private from public;grant execute on function private.current_tenant_id() to authenticated;grant execute on function private.current_role() to authenticated;grant execute on function private.current_client_id() to authenticated;grant execute on function private.is_internal() to authenticated;grant execute on function private.has_role(public.app_role[]) to authenticated;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(user_id,full_name,status,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),'pending','guard') on conflict(user_id) do nothing;return new;end$$;
revoke execute on function public.handle_new_user() from public,anon,authenticated;grant execute on function public.handle_new_user() to supabase_auth_admin;create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.touch_updated_at() returns trigger language plpgsql security invoker set search_path='' as $$begin new.updated_at=now();return new;end$$;revoke execute on function public.touch_updated_at() from public,anon;grant execute on function public.touch_updated_at() to authenticated;
do $$declare t text;begin for t in select table_name from information_schema.columns where table_schema='public' and column_name='updated_at' loop execute format('create trigger %I_touch before update on public.%I for each row execute function public.touch_updated_at()',t,t);end loop;end$$;

create or replace function private.audit_row_change() returns trigger language plpgsql security definer set search_path='' as $$declare tid uuid;eid uuid;begin tid:=coalesce((to_jsonb(new)->>'tenant_id')::uuid,(to_jsonb(old)->>'tenant_id')::uuid);eid:=coalesce((to_jsonb(new)->>'id')::uuid,(to_jsonb(old)->>'id')::uuid);insert into public.audit_log(tenant_id,actor_user_id,action,entity_type,entity_id,old_data,new_data) values(tid,(select auth.uid()),TG_OP,TG_TABLE_NAME,eid,to_jsonb(old),to_jsonb(new));return coalesce(new,old);end$$;
revoke all on function private.audit_row_change() from public;grant execute on function private.audit_row_change() to authenticated;
do $$declare t text;begin for t in select table_name from information_schema.columns where table_schema='public' and column_name='tenant_id' and table_name<>'audit_log' loop execute format('create trigger %I_audit after insert or update or delete on public.%I for each row execute function private.audit_row_change()',t,t);end loop;end$$;

do $$declare t text;begin for t in select table_name from information_schema.tables where table_schema='public' and table_type='BASE TABLE' and table_name<>'spatial_ref_sys' loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
grant select,insert,update,delete on all tables in schema public to authenticated;grant usage,select on all sequences in schema public to authenticated;

create policy tenants_select on public.tenants for select to authenticated using(id=(select private.current_tenant_id()) or (select private.has_role(array['platform_owner','super_administrator']::public.app_role[])));
create policy tenants_manage on public.tenants for all to authenticated using((select private.has_role(array['platform_owner','super_administrator']::public.app_role[]))) with check((select private.has_role(array['platform_owner','super_administrator']::public.app_role[])));
create policy profiles_select on public.profiles for select to authenticated using(user_id=(select auth.uid()) or (tenant_id=(select private.current_tenant_id()) and (select private.is_internal())));
create policy profiles_update_self on public.profiles for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy profiles_admin on public.profiles for all to authenticated using((select private.has_role(array['platform_owner','super_administrator','administrator','hr']::public.app_role[])) and tenant_id=(select private.current_tenant_id())) with check((select private.has_role(array['platform_owner','super_administrator','administrator','hr']::public.app_role[])) and tenant_id=(select private.current_tenant_id()));

do $$declare t text;begin for t in select table_name from information_schema.columns where table_schema='public' and column_name='tenant_id' and table_name not in ('tenants','profiles','audit_log') loop execute format('create policy %I_select on public.%I for select to authenticated using(tenant_id=(select private.current_tenant_id()) and (select private.is_internal()))',t,t);execute format('create policy %I_insert on public.%I for insert to authenticated with check(tenant_id=(select private.current_tenant_id()) and (select private.is_internal()))',t,t);execute format('create policy %I_update on public.%I for update to authenticated using(tenant_id=(select private.current_tenant_id()) and (select private.is_internal())) with check(tenant_id=(select private.current_tenant_id()) and (select private.is_internal()))',t,t);execute format('create policy %I_delete on public.%I for delete to authenticated using(tenant_id=(select private.current_tenant_id()) and (select private.has_role(array[''platform_owner'',''super_administrator'',''administrator'']::public.app_role[])))',t,t);end loop;end$$;

create policy clients_client_select on public.clients for select to authenticated using(tenant_id=(select private.current_tenant_id()) and id=(select private.current_client_id()));
create policy sites_client_select on public.sites for select to authenticated using(tenant_id=(select private.current_tenant_id()) and client_id=(select private.current_client_id()));
create policy incidents_client_select on public.incidents for select to authenticated using(tenant_id=(select private.current_tenant_id()) and exists(select 1 from public.sites s where s.id=incidents.site_id and s.client_id=(select private.current_client_id())));
create policy patrol_routes_client_select on public.patrol_routes for select to authenticated using(tenant_id=(select private.current_tenant_id()) and exists(select 1 from public.sites s where s.id=patrol_routes.site_id and s.client_id=(select private.current_client_id())));
create policy patrol_runs_client_select on public.patrol_runs for select to authenticated using(tenant_id=(select private.current_tenant_id()) and exists(select 1 from public.patrol_routes r join public.sites s on s.id=r.site_id where r.id=patrol_runs.route_id and s.client_id=(select private.current_client_id())));
create policy attendance_client_select on public.attendance for select to authenticated using(tenant_id=(select private.current_tenant_id()) and exists(select 1 from public.employees e join public.sites s on s.id=e.site_id where e.id=attendance.employee_id and s.client_id=(select private.current_client_id())));
create policy notifications_self_select on public.notifications for select to authenticated using(recipient_user_id=(select auth.uid()) and tenant_id=(select private.current_tenant_id()));
create policy notifications_self_update on public.notifications for update to authenticated using(recipient_user_id=(select auth.uid())) with check(recipient_user_id=(select auth.uid()));
create policy audit_select on public.audit_log for select to authenticated using(tenant_id=(select private.current_tenant_id()) and (select private.has_role(array['platform_owner','super_administrator','administrator','compliance']::public.app_role[])));
revoke update,delete on public.audit_log from authenticated;
revoke all on all tables in schema public from anon;revoke all on all functions in schema public from anon;

create or replace function public.validate_shift_assignment() returns trigger language plpgsql security invoker set search_path='' as $$begin if exists(select 1 from public.shift_assignments sa join public.shifts s on s.id=sa.shift_id where sa.employee_id=new.employee_id and sa.id<>new.id and s.starts_at<(select ends_at from public.shifts where id=new.shift_id) and s.ends_at>(select starts_at from public.shifts where id=new.shift_id)) then raise exception 'Employee already has an overlapping shift';end if;return new;end$$;
revoke execute on function public.validate_shift_assignment() from public,anon;grant execute on function public.validate_shift_assignment() to authenticated;create trigger shift_assignment_conflict before insert or update on public.shift_assignments for each row execute function public.validate_shift_assignment();

create or replace function public.refresh_compliance_status() returns trigger language plpgsql security invoker set search_path='' as $$begin if new.expiry_date is null then return new;end if;if new.expiry_date<current_date then new.status='expired';elsif new.expiry_date<=current_date+30 then new.status='expiring';else new.status='valid';end if;return new;end$$;
create trigger compliance_status before insert or update of expiry_date on public.compliance_items for each row execute function public.refresh_compliance_status();

create view public.v_site_performance with(security_invoker=true) as select s.id,s.tenant_id,s.name,s.status,(select count(*) from public.employees e where e.site_id=s.id and e.employment_status='active') active_guards,(select count(*) from public.incidents i where i.site_id=s.id and i.status in('open','under_review','escalated')) open_incidents,(select count(*) from public.posts p where p.site_id=s.id and p.status='active') active_posts from public.sites s;
grant select on public.v_site_performance to authenticated;
