-- Vimba Ops database foundation.
-- Tenant-aware schema, Auth profile bootstrap, RLS helpers, core operational tables and AI intelligence persistence.
create extension if not exists pgcrypto;
do $$ begin create type public.app_role as enum ('platform_owner','super_administrator','administrator','operations_manager','area_manager','site_supervisor','hr','finance','compliance','guard','client_administrator','client_user'); exception when duplicate_object then null; end $$;

create table if not exists public.tenants(id uuid primary key default gen_random_uuid(),name text not null,status text not null default 'active' check(status in('active','inactive','suspended')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.clients(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,name text not null,account_number text,status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.sites(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,client_id uuid references public.clients(id) on delete set null,name text not null,status text not null default 'active',city text,operating_hours text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.profiles(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,tenant_id uuid references public.tenants(id) on delete restrict,client_id uuid references public.clients(id) on delete set null,employee_id uuid,full_name text not null default '',role public.app_role not null default 'guard',status text not null default 'pending' check(status in('active','inactive','pending','suspended','archived')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.employees(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,employee_number text not null,full_name text not null,rank text,employment_status text not null default 'active',site_id uuid references public.sites(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,employee_number));
alter table public.profiles drop constraint if exists profiles_employee_id_fkey; alter table public.profiles add constraint profiles_employee_id_fkey foreign key(employee_id) references public.employees(id) on delete set null;
create table if not exists public.posts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,site_id uuid not null references public.sites(id) on delete cascade,name text not null,status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.assets(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,asset_number text not null,name text not null,category text,status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,asset_number));
create table if not exists public.compliance_items(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,subject_name text not null,document_type text not null,status text not null default 'valid',expiry_date date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.saved_reports(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,name text not null,report_type text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.attendance(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete cascade,attendance_date date not null,clock_in timestamptz,clock_out timestamptz,status text not null default 'on_duty',exception_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(employee_id,attendance_date));
create table if not exists public.incidents(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,site_id uuid references public.sites(id) on delete set null,reported_by uuid references auth.users(id) on delete set null,title text not null,description text not null,severity text not null check(severity in('low','medium','high','critical')),status text not null default 'open',occurred_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.patrol_routes(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,site_id uuid not null references public.sites(id) on delete cascade,name text not null,status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.patrol_runs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,route_id uuid not null references public.patrol_routes(id) on delete cascade,employee_id uuid references public.employees(id) on delete set null,status text not null default 'completed',started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.shifts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,site_id uuid not null references public.sites(id) on delete cascade,post_id uuid references public.posts(id) on delete set null,starts_at timestamptz not null,ends_at timestamptz not null,status text not null default 'planned',required_staff integer not null default 1 check(required_staff>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at>starts_at));
create table if not exists public.shift_assignments(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,shift_id uuid not null references public.shifts(id) on delete cascade,employee_id uuid not null references public.employees(id) on delete cascade,created_at timestamptz not null default now(),unique(shift_id,employee_id));
create table if not exists public.leave_types(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,name text not null,code text,status text not null default 'active',created_at timestamptz not null default now(),unique(tenant_id,name));
create table if not exists public.leave_requests(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete cascade,leave_type_id uuid not null references public.leave_types(id) on delete restrict,start_date date not null,end_date date not null,status text not null default 'pending',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date>=start_date));
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,recipient_user_id uuid not null references auth.users(id) on delete cascade,title text not null,message text not null,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.audit_log(id uuid primary key default gen_random_uuid(),tenant_id uuid references public.tenants(id) on delete set null,actor_user_id uuid references auth.users(id) on delete set null,action text not null,entity_type text not null,entity_id uuid,old_data jsonb,new_data jsonb,created_at timestamptz not null default now());
create table if not exists public.ai_analysis_runs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,requested_by uuid not null references auth.users(id) on delete restrict,analysis_type text not null,status text not null default 'running',input_scope jsonb not null default '{}'::jsonb,model_provider text,model_name text,output_summary jsonb,error_code text,created_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists public.ai_insights(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,analysis_run_id uuid not null references public.ai_analysis_runs(id) on delete cascade,generated_by uuid references auth.users(id) on delete set null,insight_type text not null,severity text not null,title text not null,summary text not null,rationale text,confidence numeric(5,4),evidence jsonb not null default '[]'::jsonb,recommended_actions jsonb not null default '[]'::jsonb,created_at timestamptz not null default now());

create index if not exists clients_tenant_idx on public.clients(tenant_id); create index if not exists sites_tenant_idx on public.sites(tenant_id); create index if not exists sites_client_idx on public.sites(client_id); create index if not exists employees_tenant_idx on public.employees(tenant_id); create index if not exists employees_site_idx on public.employees(site_id); create index if not exists assets_tenant_idx on public.assets(tenant_id); create index if not exists compliance_tenant_idx on public.compliance_items(tenant_id); create index if not exists attendance_tenant_date_idx on public.attendance(tenant_id,attendance_date); create index if not exists incidents_tenant_status_idx on public.incidents(tenant_id,status); create index if not exists incidents_site_idx on public.incidents(site_id); create index if not exists patrol_routes_tenant_idx on public.patrol_routes(tenant_id); create index if not exists patrol_runs_tenant_idx on public.patrol_runs(tenant_id); create index if not exists shifts_tenant_start_idx on public.shifts(tenant_id,starts_at); create index if not exists shift_assignments_employee_idx on public.shift_assignments(employee_id); create index if not exists leave_requests_tenant_idx on public.leave_requests(tenant_id); create index if not exists notifications_recipient_idx on public.notifications(recipient_user_id,read_at); create index if not exists audit_log_tenant_created_idx on public.audit_log(tenant_id,created_at); create index if not exists ai_runs_tenant_idx on public.ai_analysis_runs(tenant_id,created_at); create index if not exists ai_insights_tenant_idx on public.ai_insights(tenant_id,created_at);

create schema if not exists private;
create or replace function private.current_tenant_id() returns uuid language sql stable security definer set search_path='' as $$select tenant_id from public.profiles where user_id=(select auth.uid()) and status='active' limit 1$$;
create or replace function private.current_role() returns public.app_role language sql stable security definer set search_path='' as $$select role from public.profiles where user_id=(select auth.uid()) and status='active' limit 1$$;
create or replace function private.current_client_id() returns uuid language sql stable security definer set search_path='' as $$select client_id from public.profiles where user_id=(select auth.uid()) and status='active' limit 1$$;
create or replace function private.current_employee_id() returns uuid language sql stable security definer set search_path='' as $$select employee_id from public.profiles where user_id=(select auth.uid()) and status='active' limit 1$$;
create or replace function private.has_role(allowed public.app_role[]) returns boolean language sql stable security definer set search_path='' as $$select coalesce((select private.current_role())=any(allowed),false)$$;
create or replace function private.is_internal() returns boolean language sql stable security definer set search_path='' as $$select coalesce((select private.current_role()) in('platform_owner','super_administrator','administrator','operations_manager','area_manager','site_supervisor','hr','finance','compliance'),false)$$;
create or replace function private.can_access_tenant(target uuid) returns boolean language sql stable security definer set search_path='' as $$select (select private.has_role(array['platform_owner','super_administrator']::public.app_role[])) or target=(select private.current_tenant_id())$$;
grant usage on schema private to authenticated; revoke all on all functions in schema private from public,anon; grant execute on function private.current_tenant_id() to authenticated; grant execute on function private.current_role() to authenticated; grant execute on function private.current_client_id() to authenticated; grant execute on function private.current_employee_id() to authenticated; grant execute on function private.has_role(public.app_role[]) to authenticated; grant execute on function private.is_internal() to authenticated; grant execute on function private.can_access_tenant(uuid) to authenticated;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(user_id,full_name,status,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),'pending','guard') on conflict(user_id) do nothing; return new; end$$;
revoke all on function public.handle_new_user() from public,anon,authenticated; grant execute on function public.handle_new_user() to supabase_auth_admin; drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.touch_updated_at() returns trigger language plpgsql security invoker set search_path='' as $$begin new.updated_at=now(); return new; end$$; revoke execute on function public.touch_updated_at() from public,anon; grant execute on function public.touch_updated_at() to authenticated;
do $$declare t text;begin for t in select table_name from information_schema.columns where table_schema='public' and column_name='updated_at' loop execute format('create trigger %I_touch before update on public.%I for each row execute function public.touch_updated_at()',t,t); end loop;end$$;
create or replace function public.validate_shift_assignment() returns trigger language plpgsql security invoker set search_path='' as $$begin if exists(select 1 from public.shift_assignments sa join public.shifts existing on existing.id=sa.shift_id join public.shifts incoming on incoming.id=new.shift_id where sa.employee_id=new.employee_id and sa.id<>new.id and existing.starts_at<incoming.ends_at and existing.ends_at>incoming.starts_at) then raise exception 'Employee already has an overlapping shift';end if;return new;end$$;
revoke execute on function public.validate_shift_assignment() from public,anon; grant execute on function public.validate_shift_assignment() to authenticated; create trigger shift_assignment_conflict before insert or update on public.shift_assignments for each row execute function public.validate_shift_assignment();
create or replace function public.refresh_compliance_status() returns trigger language plpgsql security invoker set search_path='' as $$begin if new.expiry_date is null then return new;end if;if new.expiry_date<current_date then new.status='expired';elsif new.expiry_date<=current_date+30 then new.status='expiring';else new.status='valid';end if;return new;end$$;
revoke execute on function public.refresh_compliance_status() from public,anon; grant execute on function public.refresh_compliance_status() to authenticated; create trigger compliance_status before insert or update of expiry_date on public.compliance_items for each row execute function public.refresh_compliance_status();

do $$declare t text;begin for t in select table_name from information_schema.tables where table_schema='public' and table_type='BASE TABLE' loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
grant select,insert,update,delete on all tables in schema public to authenticated; grant usage,select on all sequences in schema public to authenticated; revoke all on all tables in schema public from anon; revoke all on all functions in schema public from anon;

create policy tenants_select on public.tenants for select to authenticated using(id=(select private.current_tenant_id()) or (select private.has_role(array['platform_owner','super_administrator']::public.app_role[])));
create policy profiles_select on public.profiles for select to authenticated using(user_id=(select auth.uid()) or ((tenant_id=(select private.current_tenant_id())) and (select private.is_internal())) or (select private.has_role(array['platform_owner','super_administrator']::public.app_role[])));
create policy profiles_update_self on public.profiles for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));

do $$declare t text;begin for t in select table_name from information_schema.columns where table_schema='public' and column_name='tenant_id' and table_name not in('tenants','profiles','audit_log') loop execute format('create policy %I_select on public.%I for select to authenticated using((select private.can_access_tenant(tenant_id)) and (select private.is_internal()))',t,t); execute format('create policy %I_insert on public.%I for insert to authenticated with check((select private.can_access_tenant(tenant_id)) and (select private.is_internal()))',t,t); execute format('create policy %I_update on public.%I for update to authenticated using((select private.can_access_tenant(tenant_id)) and (select private.is_internal())) with check((select private.can_access_tenant(tenant_id)) and (select private.is_internal()))',t,t); execute format('create policy %I_delete on public.%I for delete to authenticated using((select private.can_access_tenant(tenant_id)) and (select private.has_role(array[''platform_owner'',''super_administrator'',''administrator'']::public.app_role[])))',t,t);end loop;end$$;
create policy audit_select on public.audit_log for select to authenticated using(tenant_id=(select private.current_tenant_id()) and (select private.has_role(array['platform_owner','super_administrator','administrator','compliance']::public.app_role[])));
revoke insert,update,delete on public.audit_log from authenticated;
create view public.v_site_performance with(security_invoker=true) as select s.id,s.tenant_id,s.name,s.status,(select count(*) from public.employees e where e.site_id=s.id and e.employment_status='active') active_guards,(select count(*) from public.incidents i where i.site_id=s.id and i.status in('open','under_review','escalated')) open_incidents,(select count(*) from public.posts p where p.site_id=s.id and p.status='active') active_posts from public.sites s;
grant select on public.v_site_performance to authenticated;